name: macOS

on:
  push:
    branches:
      - master
      - beta
      - stable
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Tests (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        go: [ 'stable' ]
        os: [ macos-latest ]
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Show versions
        run: go version

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests on ${{ matrix.os }}
        run: |
          go test -v -race -cover -tags=debug ./tests/init
          go test -v -race -cover -tags=debug ./tests/happy_scenarios
          go test -v -race -cover -tags=debug ./tests/interfaces
          go test -v -race -cover -tags=debug ./tests/issues
          go test -v -race -cover -tags=debug ./tests/stress
          go test -v -race -cover -tags=debug ./tests/disabled_vertices

